/**
 * Hikers Horizon — Trek Knowledge Base
 * Complete data scraped from hikershorizon.in
 */

const COMPANY_INFO = {
  name: "Hikers Horizon",
  tagline: "Your Gateway to the Wild",
  email: "hikershorizon@gmail.com",
  phone: "+91 99026 53393",
  location: "Yelahanka, Bangalore, India - 560064",
  website: "https://hikershorizon.in",
  instagram: "https://instagram.com/hikers_horizon",
  operatingFrom: "Bangalore",
  established: "2026",
};

const TREKS = {
  // ═══════════════════ SUNRISE TREKS ═══════════════════
  skandagiri: {
    name: "Skandagiri Sunrise Trek",
    slug: "Sunrise/Skandagiri-sunrise-trek-from-bangalore",
    category: "sunrise",
    difficulty: "Easy-Moderate",
    duration: "1 Night",
    altitude: "1,350 m",
    distance: "~7 km",
    location: "Chikkaballapur, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 999, withTransport: 1399 },
    highlights: [
      "Stunning sunrise above the clouds",
      "Night trek experience",
      "Ancient Skandagiri Fort ruins",
      "Sea of clouds view",
    ],
    bestSeason: "September to February",
    includes: [
      "Trek guide & support",
      "Permits & entry fees",
      "First aid support",
    ],
    bookingPage: "booking-skandagiri",
  },

  nandihills: {
    name: "Nandi Hills Sunrise Trek",
    slug: "Sunrise/Nandihills-sunrise-trek",
    category: "sunrise",
    difficulty: "Easy",
    duration: "Half Day",
    altitude: "1,478 m",
    distance: "~4 km",
    location: "Chikkaballapur, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 299, withTransport: 899 },
    highlights: [
      "Most popular sunrise point near Bangalore",
      "Tipu Sultan's Summer Residence",
      "Paragliding opportunities",
      "Scenic cycling routes",
    ],
    bestSeason: "Year-round (best Oct-Feb)",
    includes: [
      "Trek guide",
      "Entry fees",
      "First aid support",
    ],
    bookingPage: "booking-nandihills",
  },

  savandurga: {
    name: "Savandurga Sunrise Trek",
    slug: "Sunrise/Savandurga-sunrise-trek",
    category: "sunrise",
    difficulty: "Moderate",
    duration: "Half Day",
    altitude: "1,226 m",
    distance: "~3 km",
    location: "Ramanagara, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 999, withTransport: 1399 },
    highlights: [
      "Asia's largest monolith hill",
      "Stunning sunrise views",
      "Rocky terrain adventure",
      "Manchanabele Dam nearby",
    ],
    bestSeason: "October to February",
    includes: ["Trek guide", "Permits", "First aid support"],
    bookingPage: "booking-savandurga",
  },

  anthargange: {
    name: "Anthargange Night Trek",
    slug: "Sunrise/Anthargange-trek",
    category: "sunrise",
    difficulty: "Moderate",
    duration: "1 Night",
    altitude: "1,226 m",
    distance: "~4 km",
    location: "Kolar, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 799, withTransport: 1199 },
    highlights: [
      "Cave exploration",
      "Night trek with stargazing",
      "Volcanic rock formations",
      "Bonfire & camping vibes",
    ],
    bestSeason: "October to March",
    includes: ["Trek guide", "Permits", "First aid", "Torches"],
    bookingPage: "booking-anthargange",
  },

  makalidurga: {
    name: "Makalidurga Sunrise Trek",
    slug: "Sunrise/Makalidurga-sunrise-trek",
    category: "sunrise",
    difficulty: "Moderate",
    duration: "Half Day",
    altitude: "1,117 m",
    distance: "~5 km",
    location: "Doddaballapur, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 799, withTransport: 1199 },
    highlights: [
      "Railway track walk to base",
      "Ruined Makalidurga Fort",
      "Panoramic sunrise views",
      "Off-the-beaten-path experience",
    ],
    bestSeason: "October to February",
    includes: ["Trek guide", "Permits", "First aid support"],
    bookingPage: "booking-makalidurga",
  },

  kuntibetta: {
    name: "Kuntibetta Sunrise Trek",
    slug: "Sunrise/Kuntibetta-sunrise-trek",
    category: "sunrise",
    difficulty: "Easy",
    duration: "Half Day",
    altitude: "930 m",
    distance: "~3 km",
    location: "Pandavapura, Mandya, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 799, withTransport: 1199 },
    highlights: [
      "Mythological significance (Pandavas)",
      "Beautiful twin hills",
      "River Cauvery view",
      "Peaceful & less crowded",
    ],
    bestSeason: "October to March",
    includes: ["Trek guide", "Permits", "First aid support"],
    bookingPage: "booking-kuntibetta",
  },

  uttaribetta: {
    name: "Uttaribetta Sunrise Trek",
    slug: "Sunrise/Uttaribetta-sunrise-trek",
    category: "sunrise",
    difficulty: "Easy",
    duration: "Half Day",
    altitude: "900 m",
    distance: "~2 km",
    location: "Doddaballapur, Karnataka",
    pickupFrom: "Bangalore",
    prices: { selfDrive: 799, withTransport: 1199 },
    highlights: [
      "Small but scenic hillock",
      "Temple at the summit",
      "Perfect for beginners",
      "Quick getaway from Bangalore",
    ],
    bestSeason: "October to February",
    includes: ["Trek guide", "Permits", "First aid support"],
    bookingPage: "booking-uttaribetta",
  },

  // ═══════════════════ TWO-DAY TREKS ═══════════════════
  gokarna: {
    name: "Gokarna Beach Trek",
    slug: "Twodays/Gokarna",
    category: "twoday",
    difficulty: "Easy-Moderate",
    duration: "2 Days / 3 Nights",
    distance: "~10 km coastal trek",
    location: "Gokarna, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "Coastal trekking along 5 pristine beaches",
      "Belekan → Paradise → Half Moon → Om → Kudle Beach",
      "Mirjan Fort exploration",
      "Murudeshwar Temple visit",
      "Honnavara Backwater Boating",
    ],
    bestSeason: "October to March",
    includes: [
      "To and fro transport from Bengaluru",
      "Two Veg Breakfasts & One Dinner",
      "Beachside Stay (Homestay/Shacks)",
      "Trek Lead & Support Team",
      "First Aid Kit",
    ],
    bookingPage: "booking-gokarna",
  },

  kodachadri: {
    name: "Kodachadri Trek",
    slug: "Twodays/Kodachadri",
    category: "twoday",
    difficulty: "Moderate",
    duration: "2 Days / 1 Night",
    altitude: "1,343 m",
    distance: "~15 km",
    location: "Shimoga, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3199 },
    highlights: [
      "Majestic Western Ghats peak",
      "Hidlumane Falls",
      "Sunset Point view",
      "Dense Shola forest trek",
      "Sarvajna Peetha at summit",
    ],
    bestSeason: "October to February",
    includes: [
      "Transport from Bangalore",
      "Accommodation",
      "Meals (Breakfast + Dinner)",
      "Trek guide",
      "First aid",
    ],
    bookingPage: "booking-kodachadri",
  },

  kuduremukha: {
    name: "Kuduremukha Trek",
    slug: "Twodays/Kuduremukha",
    category: "twoday",
    difficulty: "Moderate-Hard",
    duration: "2 Days / 1 Night",
    altitude: "1,894 m",
    distance: "~20 km",
    location: "Chikmagalur, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "Horse-face shaped peak",
      "Rolling grassland trails",
      "Stunning panoramic views",
      "Dense forests & waterfalls",
    ],
    bestSeason: "October to February",
    includes: [
      "Transport from Bangalore",
      "Accommodation",
      "Meals",
      "Trek guide & support",
      "Permits",
    ],
    bookingPage: "booking-kudremukha",
  },

  kumaraparvatha: {
    name: "Kumaraparvatha Trek",
    slug: "Twodays/Kumaraparvatha",
    category: "twoday",
    difficulty: "Hard",
    duration: "2 Days / 1 Night",
    altitude: "1,712 m",
    distance: "~22 km",
    location: "Dakshina Kannada, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3999 },
    highlights: [
      "Most challenging trek in Karnataka",
      "Pushpagiri peak views",
      "Shesha Parvatha camping",
      "Dense Bhattara Mane forest",
    ],
    bestSeason: "October to February",
    includes: [
      "Transport from Bangalore",
      "Camping equipment",
      "Meals",
      "Trek guide & support",
      "Permits",
    ],
    bookingPage: "booking-kumaraparvatha",
  },

  netravathi: {
    name: "Netravathi Peak Trek",
    slug: "Twodays/Netravathi",
    category: "twoday",
    difficulty: "Moderate-Hard",
    duration: "2 Days / 1 Night",
    altitude: "1,655 m",
    distance: "~16 km",
    location: "Dakshina Kannada, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "Origin of River Netravathi",
      "Pristine Western Ghats trail",
      "Shola forest ecosystem",
      "Breathtaking summit views",
    ],
    bestSeason: "November to February",
    includes: [
      "Transport from Bangalore",
      "Accommodation",
      "Meals",
      "Trek guide & support",
      "Permits",
    ],
    bookingPage: "booking-netravathi",
  },

  tadiandamol: {
    name: "Tadiandamol Trek",
    slug: "Twodays/Tadiandamol",
    category: "twoday",
    difficulty: "Moderate",
    duration: "2 Days / 1 Night",
    altitude: "1,748 m",
    distance: "~16 km",
    location: "Coorg, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "Highest peak in Coorg",
      "Coffee & spice plantations",
      "Nalaknad Palace visit",
      "Rolling green meadows",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Accommodation",
      "Meals",
      "Trek guide",
      "Permits",
    ],
    bookingPage: "booking-tadiandamol",
  },

  // ═══════════════════ BACKPACKING TRIPS ═══════════════════
  wayanad: {
    name: "Wayanad Backpacking Trip",
    slug: "Backpacking/Wayanad",
    category: "backpacking",
    difficulty: "Easy-Moderate",
    duration: "2 Days / 1 Night",
    location: "Wayanad, Kerala",
    pickupFrom: "Bangalore",
    prices: { standard: 3699 },
    highlights: [
      "Edakkal Caves",
      "Banasura Sagar Dam",
      "Chembra Peak heart-shaped lake",
      "Wayanad Wildlife Sanctuary",
      "Bamboo rafting",
    ],
    bestSeason: "September to March",
    includes: [
      "Transport from Bangalore",
      "Resort accommodation",
      "Meals",
      "Sightseeing",
      "Guide",
    ],
    bookingPage: "booking-wayanad",
  },

  chikmagaluru: {
    name: "Chikmagaluru Backpacking Trip",
    slug: "Backpacking/Chikmagaluru",
    category: "backpacking",
    difficulty: "Easy",
    duration: "2 Days / 1 Night",
    location: "Chikmagaluru, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "Coffee plantation tours",
      "Mullayanagiri Peak",
      "Baba Budangiri",
      "Hebbe Falls",
      "Scenic drives",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Homestay accommodation",
      "Meals",
      "Sightseeing",
    ],
    bookingPage: "booking-chikmagalur",
  },

  coorg2days: {
    name: "Coorg Backpacking Trip (2 Days)",
    slug: "Backpacking/Coorg2days",
    category: "backpacking",
    difficulty: "Easy",
    duration: "2 Days / 1 Night",
    location: "Coorg (Kodagu), Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 2999 },
    highlights: [
      "Abbey Falls",
      "Raja's Seat",
      "Dubare Elephant Camp",
      "Coffee plantation visit",
      "Golden Temple",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Resort/Homestay accommodation",
      "Meals",
      "Sightseeing",
    ],
    bookingPage: "booking-coorg",
  },

  coorg3days: {
    name: "Coorg Backpacking Trip (3 Days)",
    slug: "Backpacking/Coorg3days",
    category: "backpacking",
    difficulty: "Easy",
    duration: "3 Days / 2 Nights",
    location: "Coorg (Kodagu), Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 4999 },
    highlights: [
      "Comprehensive Coorg experience",
      "Tadiandamol trek + sightseeing",
      "Abbey Falls & Iruppu Falls",
      "Namdroling Monastery",
      "River rafting at Dubare",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Accommodation (2 nights)",
      "All meals",
      "Activities & sightseeing",
    ],
    bookingPage: "booking-coorg3days",
  },

  hampi: {
    name: "Hampi Heritage Trip",
    slug: "Backpacking/Hampi",
    category: "backpacking",
    difficulty: "Easy",
    duration: "2 Days / 1 Night",
    location: "Hampi, Karnataka",
    pickupFrom: "Bangalore",
    prices: { standard: 3499 },
    highlights: [
      "UNESCO World Heritage Site",
      "Virupaksha Temple",
      "Stone Chariot & Vittala Temple",
      "Tungabhadra River coracle ride",
      "Matanga Hill sunset",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Accommodation",
      "Meals",
      "Guide & sightseeing",
    ],
    bookingPage: "booking-hampi",
  },

  kodaikanal: {
    name: "Kodaikanal Backpacking Trip",
    slug: "Backpacking/Kodaikanal",
    category: "backpacking",
    difficulty: "Easy",
    duration: "3 Days / 2 Nights",
    location: "Kodaikanal, Tamil Nadu",
    pickupFrom: "Bangalore",
    prices: { standard: 4499 },
    highlights: [
      "Princess of Hill Stations",
      "Kodaikanal Lake boating",
      "Coaker's Walk",
      "Pillar Rocks",
      "Dolphin's Nose viewpoint",
      "Pine Forest",
    ],
    bestSeason: "October to March",
    includes: [
      "Transport from Bangalore",
      "Hotel accommodation",
      "Meals",
      "Sightseeing",
    ],
    bookingPage: "booking-kodaikanal",
  },

  munnar: {
    name: "Munnar & Kolukkumalai Adventure",
    slug: "Backpacking/Munnar",
    category: "backpacking",
    difficulty: "Easy",
    duration: "2 Days / 1 Night",
    location: "Munnar, Kerala",
    pickupFrom: "Bangalore",
    prices: { standard: 5199 },
    highlights: [
      "Kolukkumalai Sunrise Jeep Ride",
      "Phantom Hills Sunset Trek",
      "Signal Point Viewpoint",
      "Mattupetty Dam",
      "Traditional Kalaripayattu Show",
      "Munnar Tea Factory visit",
    ],
    bestSeason: "September to May",
    includes: [
      "Transport from Bangalore",
      "Campsite Tent Stay (1 night)",
      "Meals (2 Breakfasts, 1 Dinner)",
      "Forest/Trek Guide",
    ],
    bookingPage: "booking-munnar",
  },
};

// FAQ Knowledge Base
const FAQ = {
  cancellation:
    "Our cancellation policy: Full refund if cancelled 7+ days before the trek. 50% refund for 3-7 days. No refund within 3 days. Visit: https://hikershorizon.in/Cancellation",
  payment:
    "We accept all UPI apps, credit/debit cards, net banking via Razorpay. Payments are 100% secure.",
  groupSize:
    "Our treks typically have 15-30 people per batch. We also offer corporate group treks! Contact us for custom packages.",
  fitness:
    "Most sunrise treks are beginner-friendly. Two-day treks need moderate fitness. Kumaraparvatha requires good stamina. We recommend basic walking/jogging preparation.",
  whatToBring:
    "Essential items: 2L water bottles, comfortable trekking shoes, backpack, raincoat, torch/headlamp, ID proof (original + Xerox), personal medications, energy bars/dry fruits.",
  transport:
    "All treks include pick-up and drop from Bangalore. Pickup points include Majestic, Silk Board, and Electronic City.",
  weather:
    "Best trekking season is October to March. Monsoon treks (July-Sep) are available but may have leeches and slippery trails.",
  safety:
    "All treks have certified trek leads, first aid kits, and emergency contacts. We maintain a max group-to-guide ratio for safety.",
  age: "Minimum age is 10 years for sunrise treks and 14 years for two-day treks. Maximum recommended age is 55 (subject to fitness).",
  corporate:
    "We offer customized corporate trek packages, team-building activities, and outdoor retreats. Email us at hikershorizon@gmail.com for custom quotes.",
};

module.exports = { COMPANY_INFO, TREKS, FAQ };
